YOUNG_REINFORCEMENT = 209e9
YOUNG_CONCRETE = 30e9
POISSON_REINFORCEMENT = 0.3
POISSON_CONCRETE = 0.2

MODEL_DATABASE_NAME = 'C:/temp/model-test-35'

MODEL_NAME = 'Hollow-Concrete'

SOLID_MATERIAL_NAME = 'Concrete'
REINFORCEMENT_MATERIAL_NAME = 'Steel'

SOLID_PART_NAME = 'Concrete-Cube'
REINFORCEMENT_PART_NAME = 'Steel-Rod'

SOLID_ASSEMBLY_NAME= 'Concrete-Cube-1'
REINFORCEMENT_ASSEMBLY_NAME = 'Steel-Rod-{}'

JOB_NAME = 'Job-1'
